### ISSUE TITLE
Unable to Connect from Kubernetes using Cert-Manager (Getting: ValidationError: 1 validation error for NewAccountPayload  | termsOfServiceAgreed)

### ISSUE THREAD

**Issue by nforesperance** [knrdl/acme-ca-server#105]
I have deployed the acme-ca-server on a virtual machine and it is running well. I created an issurer with this link:
```yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # The ACME server URL
    server: https://my-host/acme/directory
    # Email address used for ACME registration
    email: my-email@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx
```
It is running well and i can acess the web ui. But when i try to create a certificate for one of my services i get this error

```bash
File "/app/acme/account/router.py", line 74, in create_or_view_account
  payload = NewAccountPayload(**data.payload.dict())
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pydantic/main.py", line 176, in __init__
  self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for NewAccountPayload
termsOfServiceAgreed
Input should be a valid boolean [type=bool_type, input_value=None, input_type=NoneType]
  For further information visit https://errors.pydantic.dev/2.7/v/bool_type
```

**Comment by mgisbers** [comment]
Just discovered the same problem.

```
INFO:     10.42.0.57:53474 - "GET / HTTP/1.1" 200 OK
Sat, Jul 20 2024 2:34:55 pm
INFO:     10.42.0.149:41876 - "GET /acme/directory HTTP/1.1" 200 OK
Sat, Jul 20 2024 2:34:55 pm
INFO:     10.42.0.149:41876 - "HEAD /acme/new-nonce HTTP/1.1" 200 OK
Sat, Jul 20 2024 2:34:55 pm
INFO:     10.42.0.149:41876 - "POST /acme/new-account HTTP/1.1" 422 Unprocessable Entity
Sat, Jul 20 2024 2:34:55 pm
ERROR:    Exception in ASGI application
2024-07-20T14:34:55.189828465+02:00   + Exception Group Traceback (most recent call last):
2024-07-20T14:34:55.189837572+02:00   |   File "/usr/local/lib/python3.12/site-packages/starlette/_utils.py", line 87, in collapse_excgroups
Sat, Jul 20 2024 2:34:55 pm
  |     yield
Sat, Jul 20 2024 2:34:55 pm
  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/base.py", line 190, in __call__
Sat, Jul 20 2024 2:34:55 pm
  |     async with anyio.create_task_group() as task_group:
Sat, Jul 20 2024 2:34:55 pm
  |   File "/usr/local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 680, in __aexit__
Sat, Jul 20 2024 2:34:55 pm
  |     raise BaseExceptionGroup(
Sat, Jul 20 2024 2:34:55 pm
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
Sat, Jul 20 2024 2:34:55 pm
  +-+---------------- 1 ----------------
2024-07-20T14:34:55.189893902+02:00     | Traceback (most recent call last):
Sat, Jul 20 2024 2:34:55 pm
    |   File "/usr/local/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 411, in run_asgi
Sat, Jul 20 2024 2:34:55 pm
    |     result = await app(  # type: ignore[func-returns-value]
Sat, Jul 20 2024 2:34:55 pm
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sat, Jul 20 2024 2:34:55 pm
    |   File "/usr/local/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
Sat, Jul 20 2024 2:34:55 pm
    |     return await self.app(scope, receive, send)
2024-07-20T14:34:55.189946871+02:00     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sat, Jul 20 2024 2:34:55 pm
    |   File "/usr/local/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
2024-07-20T14:34:55.189959885+02:00     |     await super().__call__(scope, receive, send)
Sat, Jul 20 2024 2:34:55 pm
    |   File "/usr/local/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
2024-07-20T14:34:55.189972783+02:00     |     await self.middleware_stack(scope, receive, send)
Sat, Jul 20 2024 2:34:55 pm
    |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
Sat, Jul 20 2024 2:34:55 pm
    |     raise exc
Sat, Jul 20 2024 2:34:55 pm
    |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-07-20T14:34:55.189998376+02:00     |     await self.app(scope, receive, _send)
2024-07-20T14:34:55.190004681+02:00     |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/base.py", line 189, in __call__
Sat, Jul 20 2024 2:34:55 pm
    |     with collapse_excgroups():
Sat, Jul 20 2024 2:34:55 pm
    |   File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__
2024-07-20T14:34:55.190023791+02:00     |     self.gen.throw(value)
2024-07-20T14:34:55.190030306+02:00     |   File "/usr/local/lib/python3.12/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
Sat, Jul 20 2024 2:34:55 pm
    |     raise exc
2024-07-20T14:34:55.190042957+02:00     |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/base.py", line 191, in __call__
2024-07-20T14:34:55.190049449+02:00     |     response = await self.dispatch_func(request, call_next)
Sat, Jul 20 2024 2:34:55 pm
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-20T14:34:55.190072379+02:00     |   File "/app/web/middleware.py", line 43, in dispatch
Sat, Jul 20 2024 2:34:55 pm
    |     response = await call_next(request)
2024-07-20T14:34:55.190085868+02:00     |                ^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-20T14:34:55.190092132+02:00     |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/base.py", line 165, in call_next
Sat, Jul 20 2024 2:34:55 pm
    |     raise app_exc
2024-07-20T14:34:55.190104543+02:00     |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/base.py", line 151, in coro
Sat, Jul 20 2024 2:34:55 pm
    |     await self.app(scope, receive_or_disconnect, send_no_error)
2024-07-20T14:34:55.190117097+02:00     |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
Sat, Jul 20 2024 2:34:55 pm
    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-07-20T14:34:55.190129601+02:00     |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
Sat, Jul 20 2024 2:34:55 pm
    |     raise exc
Sat, Jul 20 2024 2:34:55 pm
    |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
Sat, Jul 20 2024 2:34:55 pm
    |     await app(scope, receive, sender)
2024-07-20T14:34:55.190154421+02:00     |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 756, in __call__
2024-07-20T14:34:55.190160743+02:00     |     await self.middleware_stack(scope, receive, send)
Sat, Jul 20 2024 2:34:55 pm
    |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 776, in app
Sat, Jul 20 2024 2:34:55 pm
    |     await route.handle(scope, receive, send)
2024-07-20T14:34:55.190179376+02:00     |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 297, in handle
Sat, Jul 20 2024 2:34:55 pm
    |     await self.app(scope, receive, send)
Sat, Jul 20 2024 2:34:55 pm
    |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 77, in app
Sat, Jul 20 2024 2:34:55 pm
    |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
Sat, Jul 20 2024 2:34:55 pm
    |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-07-20T14:34:55.190212856+02:00     |     raise exc
Sat, Jul 20 2024 2:34:55 pm
    |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-07-20T14:34:55.190234125+02:00     |     await app(scope, receive, sender)
Sat, Jul 20 2024 2:34:55 pm
    |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 72, in app
Sat, Jul 20 2024 2:34:55 pm
    |     response = await func(request)
2024-07-20T14:34:55.190252993+02:00     |                ^^^^^^^^^^^^^^^^^^^
2024-07-20T14:34:55.190259275+02:00     |   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 278, in app
Sat, Jul 20 2024 2:34:55 pm
    |     raw_response = await run_endpoint_function(
2024-07-20T14:34:55.190271904+02:00     |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sat, Jul 20 2024 2:34:55 pm
    |   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
Sat, Jul 20 2024 2:34:55 pm
    |     return await dependant.call(**values)
Sat, Jul 20 2024 2:34:55 pm
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sat, Jul 20 2024 2:34:55 pm
    |   File "/app/acme/account/router.py", line 74, in create_or_view_account
Sat, Jul 20 2024 2:34:55 pm
    |     payload = NewAccountPayload(**data.payload.dict())
Sat, Jul 20 2024 2:34:55 pm
    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-20T14:34:55.190326906+02:00     |   File "/usr/local/lib/python3.12/site-packages/pydantic/main.py", line 176, in __init__
Sat, Jul 20 2024 2:34:55 pm
    |     self.__pydantic_validator__.validate_python(data, self_instance=self)
2024-07-20T14:34:55.190339742+02:00     | pydantic_core._pydantic_core.ValidationError: 1 validation error for NewAccountPayload
Sat, Jul 20 2024 2:34:55 pm
    | termsOfServiceAgreed
Sat, Jul 20 2024 2:34:55 pm
    |   Input should be a valid boolean [type=bool_type, input_value=None, input_type=NoneType]
2024-07-20T14:34:55.190358621+02:00     |     For further information visit https://errors.pydantic.dev/2.7/v/bool_type
Sat, Jul 20 2024 2:34:55 pm
    +------------------------------------
2024-07-20T14:34:55.190411164+02:00 
Sat, Jul 20 2024 2:34:55 pm
During handling of the above exception, another exception occurred:
2024-07-20T14:34:55.190425426+02:00 
Sat, Jul 20 2024 2:34:55 pm
Traceback (most recent call last):
Sat, Jul 20 2024 2:34:55 pm
  File "/usr/local/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 411, in run_asgi
Sat, Jul 20 2024 2:34:55 pm
    result = await app(  # type: ignore[func-returns-value]
Sat, Jul 20 2024 2:34:55 pm
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sat, Jul 20 2024 2:34:55 pm
  File "/usr/local/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
2024-07-20T14:34:55.190463145+02:00     return await self.app(scope, receive, send)
2024-07-20T14:34:55.190469369+02:00            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sat, Jul 20 2024 2:34:55 pm
  File "/usr/local/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
2024-07-20T14:34:55.190481728+02:00     await super().__call__(scope, receive, send)
2024-07-20T14:34:55.190487900+02:00   File "/usr/local/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
Sat, Jul 20 2024 2:34:55 pm
    await self.middleware_stack(scope, receive, send)
2024-07-20T14:34:55.190500161+02:00   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
Sat, Jul 20 2024 2:34:55 pm
    raise exc
Sat, Jul 20 2024 2:34:55 pm
  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-07-20T14:34:55.190519114+02:00     await self.app(scope, receive, _send)
Sat, Jul 20 2024 2:34:55 pm
  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/base.py", line 189, in __call__
2024-07-20T14:34:55.190531578+02:00     with collapse_excgroups():
2024-07-20T14:34:55.190537837+02:00   File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__
Sat, Jul 20 2024 2:34:55 pm
    self.gen.throw(value)
2024-07-20T14:34:55.190550401+02:00   File "/usr/local/lib/python3.12/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
2024-07-20T14:34:55.190556603+02:00     raise exc
2024-07-20T14:34:55.190562865+02:00   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/base.py", line 191, in __call__
Sat, Jul 20 2024 2:34:55 pm
    response = await self.dispatch_func(request, call_next)
2024-07-20T14:34:55.190575229+02:00                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-20T14:34:55.190581288+02:00   File "/app/web/middleware.py", line 43, in dispatch
Sat, Jul 20 2024 2:34:55 pm
    response = await call_next(request)
2024-07-20T14:34:55.190599749+02:00                ^^^^^^^^^^^^^^^^^^^^^^^^
Sat, Jul 20 2024 2:34:55 pm
  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/base.py", line 165, in call_next
Sat, Jul 20 2024 2:34:55 pm
    raise app_exc
Sat, Jul 20 2024 2:34:55 pm
  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/base.py", line 151, in coro
2024-07-20T14:34:55.190625074+02:00     await self.app(scope, receive_or_disconnect, send_no_error)
2024-07-20T14:34:55.190631171+02:00   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
Sat, Jul 20 2024 2:34:55 pm
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-07-20T14:34:55.190643870+02:00   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-07-20T14:34:55.190650272+02:00     raise exc
2024-07-20T14:34:55.190656423+02:00   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-07-20T14:34:55.190662880+02:00     await app(scope, receive, sender)
Sat, Jul 20 2024 2:34:55 pm
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 756, in __call__
2024-07-20T14:34:55.190697261+02:00     await self.middleware_stack(scope, receive, send)
Sat, Jul 20 2024 2:34:55 pm
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 776, in app
2024-07-20T14:34:55.190712408+02:00     await route.handle(scope, receive, send)
Sat, Jul 20 2024 2:34:55 pm
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 297, in handle
2024-07-20T14:34:55.190724984+02:00     await self.app(scope, receive, send)
Sat, Jul 20 2024 2:34:55 pm
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 77, in app
2024-07-20T14:34:55.190737558+02:00     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
Sat, Jul 20 2024 2:34:55 pm
  File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-07-20T14:34:55.190750157+02:00     raise exc
Sat, Jul 20 2024 2:34:55 pm
  File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-07-20T14:34:55.190762851+02:00     await app(scope, receive, sender)
2024-07-20T14:34:55.190768945+02:00   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 72, in app
Sat, Jul 20 2024 2:34:55 pm
    response = await func(request)
2024-07-20T14:34:55.190781321+02:00                ^^^^^^^^^^^^^^^^^^^
Sat, Jul 20 2024 2:34:55 pm
  File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 278, in app
Sat, Jul 20 2024 2:34:55 pm
    raw_response = await run_endpoint_function(
Sat, Jul 20 2024 2:34:55 pm
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-20T14:34:55.190805954+02:00   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
Sat, Jul 20 2024 2:34:55 pm
    return await dependant.call(**values)
2024-07-20T14:34:55.190818523+02:00            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sat, Jul 20 2024 2:34:55 pm
  File "/app/acme/account/router.py", line 74, in create_or_view_account
Sat, Jul 20 2024 2:34:55 pm
    payload = NewAccountPayload(**data.payload.dict())
Sat, Jul 20 2024 2:34:55 pm
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-20T14:34:55.190843393+02:00   File "/usr/local/lib/python3.12/site-packages/pydantic/main.py", line 176, in __init__
2024-07-20T14:34:55.190849587+02:00     self.__pydantic_validator__.validate_python(data, self_instance=self)
Sat, Jul 20 2024 2:34:55 pm
pydantic_core._pydantic_core.ValidationError: 1 validation error for NewAccountPayload
2024-07-20T14:34:55.190867758+02:00 termsOfServiceAgreed
Sat, Jul 20 2024 2:34:55 pm
  Input should be a valid boolean [type=bool_type, input_value=None, input_type=NoneType]
2024-07-20T14:34:55.190880054+02:00     For further information visit https://errors.pydantic.dev/2.7/v/bool_type
```

**Comment by mgisbers** [comment]
While searching for solution I found https://github.com/cert-manager/cert-manager/issues/3022#issuecomment-648992178

After setting `ACME_TERMS_OF_SERVICE_URL` variable for the `acme-ca-server` cert-manager gets connected.

**Comment by nforesperance** [comment]
Thanks alot. The account is created. But the certificates are not still granted. The certificate is stuck at: ` Issuing certificate as Secret does not exist`

**Comment by mgisbers** [comment]
That's no part of the creation issue.

Have a look to your Order and CertificateRequest objects.

P.S.: you will discover additional problems with the created certificates as they don't have a keyUsage and extendedKeyUsage. Also the CRL extension is set to critical which firefox does not like.

**Comment by knrdl** [comment]
> P.S.: you will discover additional problems with the created certificates as they don't have a keyUsage and extendedKeyUsage. Also the CRL extension is set to critical which firefox does not like.

Please elaborate on these problems. Which error is shown by firefox? What problems did you encounter because of the missing keyUsage/extendedKeyUsage?

It is easy to add those. I would set keyUsage=`digital_signature` and extendedKeyUsage=`CLIENT_AUTH`, `SERVER_AUTH`. Would that work for you, or should it be customizable (via env vars)?

**Comment by mgisbers** [comment]
Firefox shows the following error: *Certificate contains unknown critical extension.* and refuses to use the certificate at all.

Changing the CRL to critical = False solves that problem.

**Comment by mgisbers** [comment]
Let's encrypt and others limit the use of the certificates for being used as client or server certificates and make the usage critical.

```
diff --git a/app/ca/service.py b/app/ca/service.py
index dff7f435447f91620e7497a5e505f6436ac130c5..c41ad70bc5472ed96a82900f3e068d48e3294655 100644
--- a/app/ca/service.py
+++ b/app/ca/service.py
@@ -73,7 +73,18 @@ def generate_cert_sync(*, ca_key: PrivateKeyTypes, ca_cert: x509.Certificate,
         .add_extension(x509.CRLDistributionPoints(distribution_points=[x509.DistributionPoint(full_name=[
             x509.UniformResourceIdentifier(str(settings.external_url).removesuffix('/') + f'/ca/{ca_id}/crl')
         ], relative_name=None, reasons=None, crl_issuer=None)]), critical=False) \
-        .add_extension(x509.SubjectAlternativeName(general_names=[x509.DNSName(domain) for domain in san_domains]), critical=False)
+        .add_extension(x509.SubjectAlternativeName(general_names=[x509.DNSName(domain) for domain in san_domains]), critical=False) \
+        .add_extension(x509.KeyUsage(digital_signature=True,
+                                     content_commitment=False,
+                                     key_encipherment=True,
+                                     data_encipherment=False,
+                                     key_agreement=False,
+                                     key_cert_sign=False,
+                                     crl_sign=False,
+                                     encipher_only=False,
+                                     decipher_only=False), critical=True) \
+        .add_extension(x509.ExtendedKeyUsage([x509.ExtendedKeyUsageOID.CLIENT_AUTH, x509.ExtendedKeyUsageOID.SERVER_AUTH,]),
+                       critical=False)
     cert = cert_builder.sign(private_key=ca_key, algorithm=hashes.SHA512(),)
 
     cert_pem = cert.public_bytes(serialization.Encoding.PEM)
```

Fixed that by adding them fix, but setting it by parameters would be nicer.

That's what you get from letsencrypt:

```
X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage: 
                TLS Web Server Authentication, TLS Web Client Authentication
            X509v3 Basic Constraints: critical
                CA:FALSE
```

**Comment by knrdl** [comment]
> Firefox shows the following error: _Certificate contains unknown critical extension._ and refuses to use the certificate at all.

Looks like firefox only does OCSP: https://wiki.mozilla.org/CA/Revocation_Checking_in_Firefox#Revocation_Processing_for_End-Entity_Certificates

**Comment by knrdl** [comment]
> Fixed that by adding them fix, but setting it by parameters would be nicer.

Yes, it would be nicer. But I don't see a use-case. So hard-coded might be good enough for now.

**Comment by knrdl** [comment]
> That's what you get from letsencrypt:

Interesting. I only get 
```
X509v3 Key Usage critical:
Digital Signature
```

Have you configured something to get `Key Encipherment` in addition?

**Comment by nforesperance** [comment]
> Have a look at your Order and CertificateRequest objects.

Thanks alot. Here are the statuses:

**Order**: `initialState: pending` and `state: pending`
**CertificateRequest**: 
```yaml
status:
  conditions:
    - lastTransitionTime: '2024-07-20T14:09:31Z'
      message: Certificate request has been approved by cert-manager.io
      reason: cert-manager.io
      status: 'True'
      type: Approved
    - lastTransitionTime: '2024-07-20T14:09:32Z'
      message: >-
        Waiting on certificate issuance from order
        default/staging-dashboard-tls-1-4266647032: "pending"
      reason: Pending
      status: 'False'
      type: Ready
```

Also @knrdl it looks like `CA_ENCRYPTION_KEY` is not optional. The setup (from the README) does not work unless it is given in my case.

**Comment by knrdl** [comment]
> Also @knrdl it looks like `CA_ENCRYPTION_KEY` is not optional. The setup (from the README) does not work unless it is given in my case.

Yes, `CA_ENCRYPTION_KEY`  is required. But a new one is generated if none is provided. That was hard to see as it was part of the stack trace ... changed it

**Comment by nforesperance** [comment]
Ok.
```python
logger.fatal('Env Var ca_encryption_key is missing, use this freshly generated key: %s', Fernet.generate_key().decode())
sys.exit(1)
```
It seems after the new one is generated, it exits. I would have thought `optional` means if it is not passed a new one would be generated and used without exiting. Something like:
```python
self.encryption_key = Fernet.generate_key().decode()
```
But I am new to this as well.

**Comment by knrdl** [comment]
> **Order**: `initialState: pending` and `state: pending`

Please check the logs. Cert-manager must be in charge of port 80 for the ordered domains. Otherwise acme-ca-server can't continue. And acme-ca-server must be allowed to send an http request to your ordered domains

**Comment by knrdl** [comment]
> It seems after the new one is generated, it exits. I would have thought `optional` means if it is not passed a new one would be generated and used without exiting. Something like:

No, that won't work because the encryption_key must always be the same, also after container restarts and also for each instance when you scale acme-ca-server

**Comment by nforesperance** [comment]
> 
> Please check the logs. Cert-manager must be in charge of port 80 for the ordered domains. Otherwise acme-ca-server can't continue. And acme-ca-server must be allowed to send an http request to your ordered domains
>
In the logs i see this error: **propagation check failed**

```bash
"propagation check failed" err="failed to perform self check GET request 'http://<my-host>/.well-known/acme-challenge/9llmLeav-DYXnOhnMZsAMSTjGg9iF84V3UkEgMIv1z4': Get \"http://<my-host>/.well-known/acme-challenge/9llmLeav-DYXnOhnMZsAMSTjGg9iF84V3UkEgMIv1z4\": dial tcp: lookup <my-host> on 10.3.0.10:53: no such host" logger="cert-manager.challenges" resource_name="staging-dashboard-tls-1-4266647032-880637447" resource_namespace="default" resource_kind="Challenge" resource_version="v1" dnsName="<my-host>" type="HTTP-01"
```

**Comment by knrdl** [comment]
> Let's encrypt and others limit the use of the certificates for being used as client or server certificates and make the usage critical.

This should now work as expected with the docker image `ghcr.io/knrdl/acme-ca-server:edge` (edge tag)

**Comment by nforesperance** [comment]
The suprising thing is that I had a `ClusterIssuer` for `https://acme-v02.api.letsencrypt.org/directory` for some of my domains using the same `cert-manager` and works fine. When I tried adding other domains it got stuck as I described above. I thought it was an issue with the acme server or my acount so I decided to host my own server just to be faced with the same issue.

**Comment by knrdl** [comment]
> In the logs i see this error: **propagation check failed**

Looks like `<my-host>`  holds the wrong value in your setup. I'm not a k8s expert, but maybe you have to configure your ingress to handle the different domains. Or it's a typo in domain name, idk.

**Comment by mgisbers** [comment]
> ```shell
> propagation check failed
> ```

means the cert-manager controller tries to reach the file it configures for the acme server but cannot connect.

Most often that occurs when you try to add a domain that was just recently moved to a new IP address and your dns servers still resolve the old IP not aiming to the new destination.

Just start a container, connect to it and try to get the IP for your domain. If it is the wrong IP you have to wait or to tweak your dns.

**Comment by nforesperance** [comment]
> 
> Most often that occurs when you try to add a domain that was just recently moved to a new IP address and your dns servers still resolve the old IP not aiming to the new destination.
> 
> Just start a container, connect to it and try to get the IP for your domain. If it is the wrong IP you have to wait or to tweak your dns.
>

You saved my day. Thanks alot.

**Comment by nforesperance** [comment]
Thanks alot.
The ingress is up and running with the redirection to my service working well.
But every brower (Chrome, Edge, Firefox ) says the `Certificate is not valid` and there is no https.

But the Certificate in cert-manager says: `Certificate is up to date and has not expired`

**Comment by nforesperance** [comment]
For context:
The command:
```bash
openssl req -new -x509 -nodes -days 3650 -subj "/C=TestCA/O=Demo" -key ca.key -out ca.pem
```
did not work for me, I got:
```bash
problems making Certificate Request
140706765989184:error:0D07A097:asn1 encoding routines:ASN1_mbstring_ncopy:string too long:../crypto/asn1/a_mbstr.c:107:maxsize=2
```
So eventually did something like this (just to shorted the values to 2 characters):
```bash
openssl req -new -x509 -nodes -days 3650 -subj "/C=CA/O=CM" -key ca.key -out ca.pem
```
I now when look at the certificate on chrome see this:
```
**Issued By**
    Common Name (CN)	<Not Part Of Certificate>
    Organization (O)	CM
    Organizational Unit (OU)	<Not Part Of Certificate>
```

**Comment by mgisbers** [comment]
First of all:

- CN: CommonName
- OU: OrganizationalUnit
- O: Organization
- L: Locality
- S: StateOrProvinceName
- C: CountryName

so `C` is a two letter country code.

For chrome your certificate created by acme-ca-server is invalid as long as you don't add your self-signed ca - certificate to your chrome's certificate store as trusted certificate.

**Comment by nforesperance** [comment]
I see, Thanks. I get  it now, I just sort of thought those browsers would recognise the certificate. If I am understanding you well, it means, the traffic is secured even though those browsers do not recognise the certificates (because it is self-hosted).

**Comment by mgisbers** [comment]
> I see, Thanks. I get it now, I just sort of thought those browsers would recognise the certificate. If I am understanding you well, it means, the traffic is secured even though those browsers do not recognise the certificates (because it is self-hosted).

Yes, the traffic is still protected by the certificate, but the user has to acknowledge every new connection. When using kubernetes with self-signed certs you should disable HSTS (https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#hsts) otherwise your browsers will block because it learns by HSTS only to trust the server when there is a trusted and not a self-signed certificate. To come around that, just import your CA cert into the browsers trust store.

**Comment by nforesperance** [comment]
Thanks alot.
